# Generated by Django 2.2.4 on 2020-12-20 10:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('country_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], default='green', max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Spy',
            fields=[
                ('spy_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=30, unique=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Diplomat',
            fields=[
                ('dip_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('Ambassador', 'ambassador'), ('Minister', 'minister'), ("Chargé d'affaires", "Chargé d'affaires")], default="Chargé d'affaires", max_length=50)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=30)),
                ('spy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Spy')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=30, unique=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Employee')),
            ],
        ),
    ]
