# Generated by Django 2.2.4 on 2020-12-20 11:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_agent_asset_diplomat_employee_spy_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cntry',
            fields=[
                ('country_name', django_countries.fields.CountryField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
    ]
