# Generated by Django 2.2.17 on 2020-12-21 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cntry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\d\\d-\\d\\d\\d\\d\\d\\d\\d-\\d$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], default='Others', max_length=6),
        ),
    ]
