# Generated by Django 2.2.4 on 2020-12-19 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\d\\d-\\d\\d\\d\\d\\d\\d\\d-\\d$')])),
            ],
        ),
    ]
