# Generated by Django 2.2.4 on 2020-12-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
